// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modul555.Lims.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modul555.Lims.Infrastructure.Persistence.Migrations
{
 [DbContext(typeof(LimsDbContext))]
 [Migration("20260908185508_InitialCreate")]
 partial class InitialCreate
 {
 /// <inheritdoc />
 protected override void BuildTargetModel(ModelBuilder modelBuilder)
 {
#pragma warning disable 612, 618
 modelBuilder
 .HasAnnotation("ProductVersion", "10.0.11")
 .HasAnnotation("Relational:MaxIdentifierLength", 63);

 NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
 NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

 modelBuilder.Entity("Modul555.Lims.Domain.Common.AuditLogEntry", b =>
 {
 b.Property<long>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("bigint");

 NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

 b.Property<string>("Action")
 .IsRequired()
 .HasMaxLength(16)
 .HasColumnType("character varying(16)");

 b.Property<string>("Changes")
 .HasMaxLength(400)
 .HasColumnType("text");

 b.Property<string>("EntityId")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<string>("EntityType")
 .IsRequired()
 .HasMaxLength(128)
 .HasColumnType("character varying(128)");

 b.Property<DateTimeOffset>("OccurredAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UserName")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.HasKey("Id");

 b.HasIndex("OccurredAt");

 b.HasIndex("EntityType", "EntityId");

 b.ToTable("audit_log", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ControlOrder", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Comment")
 .HasMaxLength(1000)
 .HasColumnType("character varying(1000)");

 b.Property<DateTimeOffset?>("CompletedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<int>("ControlKind")
 .HasColumnType("integer");

 b.Property<Guid>("ControlProgramId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid?>("MaterialBatchId")
 .HasColumnType("uuid");

 b.Property<string>("Number")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("PlannedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid?>("ProductBatchId")
 .HasColumnType("uuid");

 b.Property<Guid?>("ProductUnitId")
 .HasColumnType("uuid");

 b.Property<Guid?>("ResponsibleEmployeeId")
 .HasColumnType("uuid");

 b.Property<int>("Source")
 .HasColumnType("integer");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("ControlProgramId");

 b.HasIndex("MaterialBatchId");

 b.HasIndex("Number")
 .IsUnique();

 b.HasIndex("ProductBatchId");

 b.HasIndex("ProductUnitId");

 b.HasIndex("ResponsibleEmployeeId");

 b.ToTable("control_orders", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.CorrectiveAction", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<Guid?>("AssignedToId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("CompletedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .IsRequired()
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<DateTime?>("DueDate")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid>("NonconformanceId")
 .HasColumnType("uuid");

 b.Property<string>("Result")
 .HasMaxLength(1000)
 .HasColumnType("character varying(1000)");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("AssignedToId");

 b.HasIndex("NonconformanceId");

 b.ToTable("corrective_actions", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.MaterialBatch", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTime>("ArrivalDate")
 .HasColumnType("timestamp with time zone");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("Decision")
 .HasColumnType("integer");

 b.Property<string>("DecisionComment")
 .HasMaxLength(1000)
 .HasColumnType("character varying(1000)");

 b.Property<DateTime?>("ManufacturedOn")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid>("NomenclatureId")
 .HasColumnType("uuid");

 b.Property<string>("Number")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<decimal>("Quantity")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<string>("QuantityUnit")
 .HasMaxLength(32)
 .HasColumnType("character varying(32)");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<DateTime?>("SupplierDocumentDate")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("SupplierDocumentNumber")
 .HasMaxLength(128)
 .HasColumnType("character varying(128)");

 b.Property<Guid>("SupplierId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid?>("WarehouseId")
 .HasColumnType("uuid");

 b.HasKey("Id");

 b.HasIndex("NomenclatureId");

 b.HasIndex("Number")
 .IsUnique();

 b.HasIndex("SupplierId");

 b.HasIndex("WarehouseId");

 b.ToTable("material_batches", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Measurement", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<bool?>("BooleanValue")
 .HasColumnType("boolean");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("MeasuredQuantityId")
 .HasColumnType("uuid");

 b.Property<decimal?>("NumericValue")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<DateTimeOffset>("RecordedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid?>("RecordedById")
 .HasColumnType("uuid");

 b.Property<int>("Replicate")
 .HasColumnType("integer");

 b.Property<int>("Source")
 .HasColumnType("integer");

 b.Property<Guid>("TestRunId")
 .HasColumnType("uuid");

 b.Property<string>("TextValue")
 .HasMaxLength(500)
 .HasColumnType("character varying(500)");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("MeasuredQuantityId");

 b.HasIndex("RecordedById");

 b.HasIndex("TestRunId");

 b.ToTable("measurements", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Nonconformance", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("ActualValue")
 .HasMaxLength(128)
 .HasColumnType("character varying(128)");

 b.Property<string>("CauseComment")
 .HasMaxLength(1000)
 .HasColumnType("character varying(1000)");

 b.Property<Guid?>("CauseId")
 .HasColumnType("uuid");

 b.Property<Guid?>("ControlOrderId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("Decision")
 .HasColumnType("integer");

 b.Property<string>("DecisionComment")
 .HasMaxLength(1000)
 .HasColumnType("character varying(1000)");

 b.Property<DateTimeOffset>("DetectedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid?>("DetectedById")
 .HasColumnType("uuid");

 b.Property<Guid?>("MaterialBatchId")
 .HasColumnType("uuid");

 b.Property<string>("NormValue")
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<string>("Number")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<string>("ParameterName")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<Guid?>("ProductBatchId")
 .HasColumnType("uuid");

 b.Property<Guid?>("ProtocolId")
 .HasColumnType("uuid");

 b.Property<int>("Stage")
 .HasColumnType("integer");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("CauseId");

 b.HasIndex("ControlOrderId");

 b.HasIndex("DetectedById");

 b.HasIndex("MaterialBatchId");

 b.HasIndex("Number")
 .IsUnique();

 b.HasIndex("ProductBatchId");

 b.HasIndex("ProtocolId");

 b.ToTable("nonconformances", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ParameterResult", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<bool?>("BooleanValue")
 .HasColumnType("boolean");

 b.Property<DateTimeOffset>("CalculatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("NormSnapshot")
 .HasMaxLength(500)
 .HasColumnType("character varying(500)");

 b.Property<decimal?>("NumericValue")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<Guid>("TestRunId")
 .HasColumnType("uuid");

 b.Property<string>("TextValue")
 .HasMaxLength(500)
 .HasColumnType("character varying(500)");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("Verdict")
 .HasColumnType("integer");

 b.HasKey("Id");

 b.HasIndex("TestRunId")
 .IsUnique();

 b.ToTable("parameter_results", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ProductBatch", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<decimal?>("DesignValue")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<int>("Kind")
 .HasColumnType("integer");

 b.Property<Guid>("NomenclatureId")
 .HasColumnType("uuid");

 b.Property<string>("Number")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTime>("ProductionDate")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid?>("ProductionLineId")
 .HasColumnType("uuid");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("NomenclatureId");

 b.HasIndex("Number")
 .IsUnique();

 b.HasIndex("ProductionLineId");

 b.ToTable("product_batches", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ProductUnit", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("ProductBatchId")
 .HasColumnType("uuid");

 b.Property<string>("SerialNumber")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("ProductBatchId");

 b.HasIndex("SerialNumber")
 .IsUnique();

 b.ToTable("product_units", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Protocol", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Conclusion")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<Guid?>("ControlOrderId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<DateTimeOffset>("IssuedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<int>("Kind")
 .HasColumnType("integer");

 b.Property<string>("Number")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<int>("OverallVerdict")
 .HasColumnType("integer");

 b.Property<string>("ResultsSnapshot")
 .HasMaxLength(400)
 .HasColumnType("text");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<Guid?>("TemplateId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("ControlOrderId");

 b.HasIndex("Number")
 .IsUnique();

 b.HasIndex("TemplateId");

 b.ToTable("protocols", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ProtocolSignature", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("EmployeeId")
 .HasColumnType("uuid");

 b.Property<int>("Kind")
 .HasColumnType("integer");

 b.Property<Guid>("ProtocolId")
 .HasColumnType("uuid");

 b.Property<int>("Role")
 .HasColumnType("integer");

 b.Property<DateTimeOffset>("SignedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("EmployeeId");

 b.HasIndex("ProtocolId", "Role", "EmployeeId")
 .IsUnique();

 b.ToTable("protocol_signatures", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Sample", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Barcode")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<Guid>("ControlOrderId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Number")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<decimal?>("Quantity")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<string>("QuantityUnit")
 .HasMaxLength(32)
 .HasColumnType("character varying(32)");

 b.Property<DateTimeOffset>("SampledAt")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid?>("SampledById")
 .HasColumnType("uuid");

 b.Property<int>("State")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid?>("WarehouseId")
 .HasColumnType("uuid");

 b.HasKey("Id");

 b.HasIndex("Barcode")
 .IsUnique();

 b.HasIndex("ControlOrderId");

 b.HasIndex("Number")
 .IsUnique();

 b.HasIndex("SampledById");

 b.HasIndex("WarehouseId");

 b.ToTable("samples", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.SampleStateHistory", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("ChangedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid?>("ChangedById")
 .HasColumnType("uuid");

 b.Property<string>("Comment")
 .HasMaxLength(500)
 .HasColumnType("character varying(500)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("FromState")
 .HasColumnType("integer");

 b.Property<Guid>("SampleId")
 .HasColumnType("uuid");

 b.Property<int>("ToState")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("ChangedById");

 b.HasIndex("SampleId");

 b.ToTable("sample_state_history", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.TestRun", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<Guid?>("AssigneeId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("CompletedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid>("ControlOrderId")
 .HasColumnType("uuid");

 b.Property<Guid>("ControlProgramParameterId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid?>("EquipmentId")
 .HasColumnType("uuid");

 b.Property<Guid?>("SampleId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("StartedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("AssigneeId");

 b.HasIndex("ControlOrderId");

 b.HasIndex("ControlProgramParameterId");

 b.HasIndex("EquipmentId");

 b.HasIndex("SampleId");

 b.ToTable("test_runs", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.TraceabilityLink", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("MaterialBatchId")
 .HasColumnType("uuid");

 b.Property<Guid>("ProductBatchId")
 .HasColumnType("uuid");

 b.Property<decimal?>("Quantity")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("MaterialBatchId");

 b.HasIndex("ProductBatchId", "MaterialBatchId")
 .IsUnique();

 b.ToTable("traceability_links", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Competency", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("CertificateNumber")
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("EmployeeId")
 .HasColumnType("uuid");

 b.Property<DateTime>("IssuedOn")
 .HasColumnType("timestamp with time zone");

 b.Property<Guid>("TestMethodId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<DateTime>("ValidUntil")
 .HasColumnType("timestamp with time zone");

 b.HasKey("Id");

 b.HasIndex("TestMethodId");

 b.HasIndex("EmployeeId", "TestMethodId")
 .IsUnique();

 b.ToTable("competencies", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.ControlProgram", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("ApprovedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("ApprovedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<int>("ControlKind")
 .HasColumnType("integer");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<bool>("IsApproved")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<Guid>("NomenclatureId")
 .HasColumnType("uuid");

 b.Property<Guid?>("ProductionLineId")
 .HasColumnType("uuid");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<Guid?>("StandardDocumentId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.HasIndex("ProductionLineId");

 b.HasIndex("StandardDocumentId");

 b.HasIndex("NomenclatureId", "ControlKind", "ProductionLineId")
 .IsUnique();

 b.ToTable("control_programs", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.ControlProgramParameter", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<int>("Aggregation")
 .HasColumnType("integer");

 b.Property<Guid>("ControlProgramId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("Frequency")
 .HasColumnType("integer");

 b.Property<bool>("IsMandatory")
 .HasColumnType("boolean");

 b.Property<int>("NormKind")
 .HasColumnType("integer");

 b.Property<decimal?>("NormMax")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<decimal?>("NormMin")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<string>("NormText")
 .HasMaxLength(500)
 .HasColumnType("character varying(500)");

 b.Property<decimal?>("PercentOfDesign")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<Guid>("QualityParameterId")
 .HasColumnType("uuid");

 b.Property<int>("Replicates")
 .HasColumnType("integer");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<Guid?>("TestMethodId")
 .HasColumnType("uuid");

 b.Property<decimal?>("Tolerance")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("ControlProgramId");

 b.HasIndex("QualityParameterId");

 b.HasIndex("TestMethodId");

 b.ToTable("control_program_parameters", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Defect", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("AppliesTo")
 .HasMaxLength(128)
 .HasColumnType("character varying(128)");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<bool>("IsCritical")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("defects", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.DocumentTemplate", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("ApproverRole")
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<bool>("CreatedOnNonconformance")
 .HasColumnType("boolean");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<int>("Kind")
 .HasColumnType("integer");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<string>("PerformerRole")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<string>("ProductionLineCode")
 .HasMaxLength(16)
 .HasColumnType("character varying(16)");

 b.Property<bool>("RequiresQualityInspector")
 .HasColumnType("boolean");

 b.Property<int>("SignatureKind")
 .HasColumnType("integer");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<int>("Stage")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.HasIndex("Kind")
 .IsUnique();

 b.ToTable("document_templates", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Employee", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<string>("FirstName")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("LastName")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b.Property<string>("MiddleName")
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<string>("Position")
 .IsRequired()
 .HasMaxLength(200)
 .HasColumnType("character varying(200)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<Guid?>("SubdivisionId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("UserName")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<string>("WorkSchedule")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.HasIndex("SubdivisionId");

 b.HasIndex("UserName")
 .IsUnique();

 b.ToTable("employees", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Equipment", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<Guid>("EquipmentTypeId")
 .HasColumnType("uuid");

 b.Property<string>("InventoryNumber")
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Manufacturer")
 .HasMaxLength(200)
 .HasColumnType("character varying(200)");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<Guid?>("ResponsibleEmployeeId")
 .HasColumnType("uuid");

 b.Property<string>("SerialNumber")
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<int>("Status")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("VerificationIntervalMonths")
 .HasColumnType("integer");

 b.Property<DateTime?>("VerificationValidUntil")
 .HasColumnType("timestamp with time zone");

 b.Property<int?>("YearOfManufacture")
 .HasColumnType("integer");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.HasIndex("EquipmentTypeId");

 b.HasIndex("ResponsibleEmployeeId");

 b.ToTable("equipment", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.EquipmentEvent", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("CertificateNumber")
 .HasMaxLength(128)
 .HasColumnType("character varying(128)");

 b.Property<string>("Comment")
 .HasMaxLength(1000)
 .HasColumnType("character varying(1000)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("EquipmentId")
 .HasColumnType("uuid");

 b.Property<DateTime>("EventDate")
 .HasColumnType("timestamp with time zone");

 b.Property<int>("Kind")
 .HasColumnType("integer");

 b.Property<string>("Organization")
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<Guid?>("PerformedById")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<DateTime?>("ValidUntil")
 .HasColumnType("timestamp with time zone");

 b.HasKey("Id");

 b.HasIndex("EquipmentId");

 b.HasIndex("PerformedById");

 b.ToTable("equipment_events", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.EquipmentType", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("equipment_types", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.MeasuredQuantity", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("Precision")
 .HasColumnType("integer");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<string>("UnitOfMeasure")
 .HasMaxLength(32)
 .HasColumnType("character varying(32)");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("VariableName")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("measured_quantities", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Nomenclature", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<Guid>("CategoryId")
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<decimal?>("DesignValue")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<string>("Grade")
 .HasMaxLength(128)
 .HasColumnType("character varying(128)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<Guid?>("RequirementStandardId")
 .HasColumnType("uuid");

 b.Property<int?>("ShelfLifeDays")
 .HasColumnType("integer");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<bool>("TrackBatches")
 .HasColumnType("boolean");

 b.Property<string>("UnitOfMeasure")
 .IsRequired()
 .HasMaxLength(32)
 .HasColumnType("character varying(32)");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("CategoryId");

 b.HasIndex("Code")
 .IsUnique();

 b.HasIndex("RequirementStandardId");

 b.ToTable("nomenclatures", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.NomenclatureCategory", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<bool>("IsRawMaterial")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("nomenclature_categories", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.NonconformanceCause", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<string>("Group")
 .HasMaxLength(128)
 .HasColumnType("character varying(128)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("nonconformance_causes", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.ProductionLine", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("production_lines", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.QualityParameter", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("AllowedValues")
 .HasMaxLength(1000)
 .HasColumnType("character varying(1000)");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("Precision")
 .HasColumnType("integer");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<string>("UnitOfMeasure")
 .HasMaxLength(32)
 .HasColumnType("character varying(32)");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("ValueKind")
 .HasColumnType("integer");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("quality_parameters", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.StandardDocument", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<bool>("IsCurrent")
 .HasColumnType("boolean");

 b.Property<int>("Kind")
 .HasColumnType("integer");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int?>("Year")
 .HasColumnType("integer");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("standard_documents", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Subdivision", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<Guid?>("ProductionLineId")
 .HasColumnType("uuid");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.HasIndex("ProductionLineId");

 b.ToTable("subdivisions", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Supplier", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Address")
 .HasMaxLength(500)
 .HasColumnType("character varying(500)");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<string>("ContactPerson")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<string>("Email")
 .HasMaxLength(200)
 .HasColumnType("character varying(200)");

 b.Property<string>("Inn")
 .HasMaxLength(12)
 .HasColumnType("character varying(12)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<string>("Phone")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("suppliers", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethod", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<int>("DefaultReplicates")
 .HasColumnType("integer");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<string>("Formula")
 .HasMaxLength(500)
 .HasColumnType("character varying(500)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<bool>("IsDestructive")
 .HasColumnType("boolean");

 b.Property<int>("LaborMinutes")
 .HasColumnType("integer");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<bool>("RequiresCompetency")
 .HasColumnType("boolean");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<Guid?>("StandardDocumentId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.HasIndex("StandardDocumentId");

 b.ToTable("test_methods", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethodEquipmentType", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("EquipmentTypeId")
 .HasColumnType("uuid");

 b.Property<bool>("IsRequired")
 .HasColumnType("boolean");

 b.Property<Guid>("TestMethodId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("EquipmentTypeId");

 b.HasIndex("TestMethodId");

 b.ToTable("test_method_equipment_types", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethodMaterial", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("NomenclatureId")
 .HasColumnType("uuid");

 b.Property<decimal>("PlannedQuantity")
 .HasPrecision(18, 4)
 .HasColumnType("numeric(18,4)");

 b.Property<Guid>("TestMethodId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("NomenclatureId");

 b.HasIndex("TestMethodId");

 b.ToTable("test_method_materials", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethodQuantity", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("MeasuredQuantityId")
 .HasColumnType("uuid");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<Guid>("TestMethodId")
 .HasColumnType("uuid");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("MeasuredQuantityId");

 b.HasIndex("TestMethodId", "MeasuredQuantityId")
 .IsUnique();

 b.ToTable("test_method_quantities", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.UserAccount", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<Guid>("EmployeeId")
 .HasColumnType("uuid");

 b.Property<bool>("IsLocked")
 .HasColumnType("boolean");

 b.Property<string>("PasswordHash")
 .IsRequired()
 .HasMaxLength(500)
 .HasColumnType("character varying(500)");

 b.Property<string>("Roles")
 .IsRequired()
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("UserName")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.HasKey("Id");

 b.HasIndex("EmployeeId");

 b.HasIndex("UserName")
 .IsUnique();

 b.ToTable("user_accounts", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Warehouse", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Code")
 .IsRequired()
 .HasMaxLength(64)
 .HasColumnType("character varying(64)");

 b.Property<DateTimeOffset>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("CreatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.Property<string>("Description")
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<bool>("IsActive")
 .HasColumnType("boolean");

 b.Property<bool>("IsQuarantineZone")
 .HasColumnType("boolean");

 b.Property<string>("Name")
 .IsRequired()
 .HasMaxLength(256)
 .HasColumnType("character varying(256)");

 b.Property<int>("SortOrder")
 .HasColumnType("integer");

 b.Property<DateTimeOffset?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UpdatedBy")
 .HasMaxLength(400)
 .HasColumnType("character varying(400)");

 b.HasKey("Id");

 b.HasIndex("Code")
 .IsUnique();

 b.ToTable("warehouses", (string)null);
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ControlOrder", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.ControlProgram", "ControlProgram")
 .WithMany()
 .HasForeignKey("ControlProgramId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Operations.MaterialBatch", "MaterialBatch")
 .WithMany("ControlOrders")
 .HasForeignKey("MaterialBatchId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.ProductBatch", "ProductBatch")
 .WithMany("ControlOrders")
 .HasForeignKey("ProductBatchId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.ProductUnit", "ProductUnit")
 .WithMany()
 .HasForeignKey("ProductUnitId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "ResponsibleEmployee")
 .WithMany()
 .HasForeignKey("ResponsibleEmployeeId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("ControlProgram");

 b.Navigation("MaterialBatch");

 b.Navigation("ProductBatch");

 b.Navigation("ProductUnit");

 b.Navigation("ResponsibleEmployee");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.CorrectiveAction", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "AssignedTo")
 .WithMany()
 .HasForeignKey("AssignedToId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.Nonconformance", "Nonconformance")
 .WithMany("Actions")
 .HasForeignKey("NonconformanceId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("AssignedTo");

 b.Navigation("Nonconformance");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.MaterialBatch", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Nomenclature", "Nomenclature")
 .WithMany()
 .HasForeignKey("NomenclatureId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.Supplier", "Supplier")
 .WithMany("Batches")
 .HasForeignKey("SupplierId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.Warehouse", "Warehouse")
 .WithMany()
 .HasForeignKey("WarehouseId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("Nomenclature");

 b.Navigation("Supplier");

 b.Navigation("Warehouse");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Measurement", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.MeasuredQuantity", "MeasuredQuantity")
 .WithMany()
 .HasForeignKey("MeasuredQuantityId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "RecordedBy")
 .WithMany()
 .HasForeignKey("RecordedById")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.TestRun", "TestRun")
 .WithMany("Measurements")
 .HasForeignKey("TestRunId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("MeasuredQuantity");

 b.Navigation("RecordedBy");

 b.Navigation("TestRun");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Nonconformance", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.NonconformanceCause", "Cause")
 .WithMany()
 .HasForeignKey("CauseId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.ControlOrder", "ControlOrder")
 .WithMany()
 .HasForeignKey("ControlOrderId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "DetectedBy")
 .WithMany()
 .HasForeignKey("DetectedById")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.MaterialBatch", "MaterialBatch")
 .WithMany()
 .HasForeignKey("MaterialBatchId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.ProductBatch", "ProductBatch")
 .WithMany()
 .HasForeignKey("ProductBatchId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.Protocol", "Protocol")
 .WithMany()
 .HasForeignKey("ProtocolId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("Cause");

 b.Navigation("ControlOrder");

 b.Navigation("DetectedBy");

 b.Navigation("MaterialBatch");

 b.Navigation("ProductBatch");

 b.Navigation("Protocol");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ParameterResult", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Operations.TestRun", "TestRun")
 .WithOne("Result")
 .HasForeignKey("Modul555.Lims.Domain.Operations.ParameterResult", "TestRunId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("TestRun");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ProductBatch", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Nomenclature", "Nomenclature")
 .WithMany()
 .HasForeignKey("NomenclatureId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.ProductionLine", "ProductionLine")
 .WithMany()
 .HasForeignKey("ProductionLineId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("Nomenclature");

 b.Navigation("ProductionLine");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ProductUnit", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Operations.ProductBatch", "ProductBatch")
 .WithMany("Units")
 .HasForeignKey("ProductBatchId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("ProductBatch");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Protocol", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Operations.ControlOrder", "ControlOrder")
 .WithMany("Protocols")
 .HasForeignKey("ControlOrderId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Reference.DocumentTemplate", "Template")
 .WithMany()
 .HasForeignKey("TemplateId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("ControlOrder");

 b.Navigation("Template");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ProtocolSignature", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "Employee")
 .WithMany()
 .HasForeignKey("EmployeeId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Operations.Protocol", "Protocol")
 .WithMany("Signatures")
 .HasForeignKey("ProtocolId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("Employee");

 b.Navigation("Protocol");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Sample", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Operations.ControlOrder", "ControlOrder")
 .WithMany("Samples")
 .HasForeignKey("ControlOrderId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "SampledBy")
 .WithMany()
 .HasForeignKey("SampledById")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Reference.Warehouse", "Warehouse")
 .WithMany()
 .HasForeignKey("WarehouseId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("ControlOrder");

 b.Navigation("SampledBy");

 b.Navigation("Warehouse");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.SampleStateHistory", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "ChangedBy")
 .WithMany()
 .HasForeignKey("ChangedById")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.Sample", "Sample")
 .WithMany("History")
 .HasForeignKey("SampleId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("ChangedBy");

 b.Navigation("Sample");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.TestRun", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "Assignee")
 .WithMany()
 .HasForeignKey("AssigneeId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.ControlOrder", "ControlOrder")
 .WithMany("TestRuns")
 .HasForeignKey("ControlOrderId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.ControlProgramParameter", "ControlProgramParameter")
 .WithMany()
 .HasForeignKey("ControlProgramParameterId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.Equipment", "Equipment")
 .WithMany()
 .HasForeignKey("EquipmentId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Operations.Sample", "Sample")
 .WithMany("TestRuns")
 .HasForeignKey("SampleId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("Assignee");

 b.Navigation("ControlOrder");

 b.Navigation("ControlProgramParameter");

 b.Navigation("Equipment");

 b.Navigation("Sample");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.TraceabilityLink", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Operations.MaterialBatch", "MaterialBatch")
 .WithMany("ProductLinks")
 .HasForeignKey("MaterialBatchId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Operations.ProductBatch", "ProductBatch")
 .WithMany("MaterialLinks")
 .HasForeignKey("ProductBatchId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("MaterialBatch");

 b.Navigation("ProductBatch");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Competency", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "Employee")
 .WithMany("Competencies")
 .HasForeignKey("EmployeeId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.TestMethod", "TestMethod")
 .WithMany("Competencies")
 .HasForeignKey("TestMethodId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.Navigation("Employee");

 b.Navigation("TestMethod");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.ControlProgram", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Nomenclature", "Nomenclature")
 .WithMany("ControlPrograms")
 .HasForeignKey("NomenclatureId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.ProductionLine", "ProductionLine")
 .WithMany("ControlPrograms")
 .HasForeignKey("ProductionLineId")
 .OnDelete(DeleteBehavior.SetNull);

 b.HasOne("Modul555.Lims.Domain.Reference.StandardDocument", "StandardDocument")
 .WithMany()
 .HasForeignKey("StandardDocumentId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("Nomenclature");

 b.Navigation("ProductionLine");

 b.Navigation("StandardDocument");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.ControlProgramParameter", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.ControlProgram", "ControlProgram")
 .WithMany("Parameters")
 .HasForeignKey("ControlProgramId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.QualityParameter", "QualityParameter")
 .WithMany()
 .HasForeignKey("QualityParameterId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.TestMethod", "TestMethod")
 .WithMany()
 .HasForeignKey("TestMethodId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("ControlProgram");

 b.Navigation("QualityParameter");

 b.Navigation("TestMethod");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Employee", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Subdivision", "Subdivision")
 .WithMany("Employees")
 .HasForeignKey("SubdivisionId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("Subdivision");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Equipment", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.EquipmentType", "EquipmentType")
 .WithMany("Items")
 .HasForeignKey("EquipmentTypeId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "ResponsibleEmployee")
 .WithMany()
 .HasForeignKey("ResponsibleEmployeeId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("EquipmentType");

 b.Navigation("ResponsibleEmployee");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.EquipmentEvent", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Equipment", "Equipment")
 .WithMany("Events")
 .HasForeignKey("EquipmentId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "PerformedBy")
 .WithMany()
 .HasForeignKey("PerformedById")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("Equipment");

 b.Navigation("PerformedBy");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Nomenclature", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.NomenclatureCategory", "Category")
 .WithMany("Items")
 .HasForeignKey("CategoryId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.StandardDocument", "RequirementStandard")
 .WithMany()
 .HasForeignKey("RequirementStandardId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("Category");

 b.Navigation("RequirementStandard");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Subdivision", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.ProductionLine", "ProductionLine")
 .WithMany()
 .HasForeignKey("ProductionLineId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("ProductionLine");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethod", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.StandardDocument", "StandardDocument")
 .WithMany()
 .HasForeignKey("StandardDocumentId")
 .OnDelete(DeleteBehavior.SetNull);

 b.Navigation("StandardDocument");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethodEquipmentType", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.EquipmentType", "EquipmentType")
 .WithMany("Methods")
 .HasForeignKey("EquipmentTypeId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.TestMethod", "TestMethod")
 .WithMany("EquipmentTypes")
 .HasForeignKey("TestMethodId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("EquipmentType");

 b.Navigation("TestMethod");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethodMaterial", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Nomenclature", "Nomenclature")
 .WithMany()
 .HasForeignKey("NomenclatureId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.TestMethod", "TestMethod")
 .WithMany("Materials")
 .HasForeignKey("TestMethodId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("Nomenclature");

 b.Navigation("TestMethod");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethodQuantity", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.MeasuredQuantity", "MeasuredQuantity")
 .WithMany()
 .HasForeignKey("MeasuredQuantityId")
 .OnDelete(DeleteBehavior.Restrict)
 .IsRequired();

 b.HasOne("Modul555.Lims.Domain.Reference.TestMethod", "TestMethod")
 .WithMany("Quantities")
 .HasForeignKey("TestMethodId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("MeasuredQuantity");

 b.Navigation("TestMethod");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.UserAccount", b =>
 {
 b.HasOne("Modul555.Lims.Domain.Reference.Employee", "Employee")
 .WithMany("Accounts")
 .HasForeignKey("EmployeeId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();

 b.Navigation("Employee");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ControlOrder", b =>
 {
 b.Navigation("Protocols");

 b.Navigation("Samples");

 b.Navigation("TestRuns");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.MaterialBatch", b =>
 {
 b.Navigation("ControlOrders");

 b.Navigation("ProductLinks");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Nonconformance", b =>
 {
 b.Navigation("Actions");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.ProductBatch", b =>
 {
 b.Navigation("ControlOrders");

 b.Navigation("MaterialLinks");

 b.Navigation("Units");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Protocol", b =>
 {
 b.Navigation("Signatures");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.Sample", b =>
 {
 b.Navigation("History");

 b.Navigation("TestRuns");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Operations.TestRun", b =>
 {
 b.Navigation("Measurements");

 b.Navigation("Result");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.ControlProgram", b =>
 {
 b.Navigation("Parameters");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Employee", b =>
 {
 b.Navigation("Accounts");

 b.Navigation("Competencies");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Equipment", b =>
 {
 b.Navigation("Events");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.EquipmentType", b =>
 {
 b.Navigation("Items");

 b.Navigation("Methods");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Nomenclature", b =>
 {
 b.Navigation("ControlPrograms");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.NomenclatureCategory", b =>
 {
 b.Navigation("Items");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.ProductionLine", b =>
 {
 b.Navigation("ControlPrograms");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Subdivision", b =>
 {
 b.Navigation("Employees");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.Supplier", b =>
 {
 b.Navigation("Batches");
 });

 modelBuilder.Entity("Modul555.Lims.Domain.Reference.TestMethod", b =>
 {
 b.Navigation("Competencies");

 b.Navigation("EquipmentTypes");

 b.Navigation("Materials");

 b.Navigation("Quantities");
 });
#pragma warning restore 612, 618
 }
 }
}
